# Generated by Django 4.2.16 on 2024-12-02 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='discord_username',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='profile_picture',
            field=models.ImageField(blank=True, default='default_profile_picture.jpg', null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='showdown_username',
            field=models.CharField(blank=True, max_length=19, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='timezone',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
    ]
