# Generated by Django 4.2.16 on 2024-12-02 00:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('leagues', '0004_team'),
        ('pokemons', '0003_pokemontypeweakness_pokemontype_pokemonspecialmove_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokemon',
            name='team',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='pokemons', to='leagues.team'),
        ),
    ]
