# Generated by Django 4.2.16 on 2024-12-03 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_customuser_discord_username_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='profile_picture',
            field=models.ImageField(blank=True, default='default_profile_picture.jpg', null=True, upload_to='profile_pictures'),
        ),
    ]
