# Generated by Django 4.2.16 on 2024-12-01 21:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('leagues', '0002_league_abbreviation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='league',
            name='logo',
            field=models.ImageField(blank=True, default='default_league_logo.png', upload_to=''),
        ),
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=50)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('REGULAR_SEASON', 'Regular Season'), ('PLAYOFFS', 'Playoffs')], default='DRAFT', max_length=15)),
                ('league', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seasons', to='leagues.league')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
