# Generated by Django 4.2.16 on 2024-12-02 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leagues', '0004_team'),
    ]

    operations = [
        migrations.AlterField(
            model_name='league',
            name='logo',
            field=models.ImageField(blank=True, default='default_league_logo.png', null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='team',
            name='logo',
            field=models.ImageField(blank=True, default='default_team_logo.png', null=True, upload_to=''),
        ),
    ]
