# Generated by Django 4.2.16 on 2024-12-03 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leagues', '0005_alter_league_logo_alter_team_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='league',
            name='logo',
            field=models.ImageField(blank=True, default='defaults/default_league_logo.png', null=True, upload_to='leagues_logos/'),
        ),
        migrations.AlterField(
            model_name='team',
            name='logo',
            field=models.ImageField(blank=True, default='defaults/default_team_logo.png', null=True, upload_to='team_logos/'),
        ),
    ]
