# Generated by Django 4.2.16 on 2024-12-05 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leagues', '0006_alter_league_logo_alter_team_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='season',
            name='status',
            field=models.CharField(choices=[('PRE_SEASON', 'Pre Season'), ('DRAFT', 'Draft'), ('REGULAR_SEASON', 'Regular Season'), ('PLAYOFFS', 'Playoffs')], default='DRAFT', max_length=15),
        ),
        migrations.AlterUniqueTogether(
            name='team',
            unique_together={('name', 'season')},
        ),
    ]
