# Generated by Django 4.2.16 on 2024-12-07 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leagues', '0007_alter_season_status_alter_team_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='league',
            name='logo',
            field=models.ImageField(blank=True, default='defaults/default_league_logo.png', null=True, upload_to='league_logos/'),
        ),
    ]
