# Generated by Django 4.2.16 on 2025-01-16 00:06

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('leagues', '0010_week_matchup_game'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='matchup',
            unique_together={('week', 'coach_one', 'coach_two')},
        ),
    ]
