# Generated by Django 4.2.16 on 2025-01-16 00:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('leagues', '0011_alter_matchup_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='loser',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loser_games', to='leagues.team'),
        ),
        migrations.AlterField(
            model_name='game',
            name='winner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='winner_games', to='leagues.team'),
        ),
        migrations.AlterField(
            model_name='matchup',
            name='coach_one',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coach_one_matchups', to='leagues.team'),
        ),
        migrations.AlterField(
            model_name='matchup',
            name='coach_two',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coach_two_matchups', to='leagues.team'),
        ),
        migrations.AlterField(
            model_name='matchup',
            name='loser',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='loser_matchups', to='leagues.team'),
        ),
        migrations.AlterField(
            model_name='matchup',
            name='winner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='winner_matchups', to='leagues.team'),
        ),
    ]
