# Generated by Django 4.2.16 on 2025-01-21 21:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('leagues', '0012_alter_game_loser_alter_game_winner_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matchup',
            name='week',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matchups', to='leagues.week'),
        ),
    ]
