# Generated by Django 4.2.16 on 2025-02-11 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leagues', '0013_alter_matchup_week'),
    ]

    operations = [
        migrations.AddField(
            model_name='week',
            name='order',
            field=models.IntegerField(default=1),
        ),
    ]
