# Generated by Django 4.2.16 on 2024-12-01 22:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('leagues', '0004_team'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pokemon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=50)),
                ('dex_number', models.IntegerField(blank=True)),
                ('hp', models.IntegerField()),
                ('attack', models.IntegerField()),
                ('defense', models.IntegerField()),
                ('special_attack', models.IntegerField()),
                ('special_defense', models.IntegerField()),
                ('speed', models.IntegerField()),
                ('base_stat_total', models.IntegerField()),
                ('weight', models.FloatField(blank=True)),
                ('height', models.FloatField(blank=True)),
                ('point_value', models.IntegerField(blank=True)),
                ('condition', models.TextField(blank=True)),
                ('sprite_url', models.TextField(blank=True)),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pokemons', to='leagues.season')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pokemons', to='leagues.team')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
