# Generated by Django 4.2.16 on 2025-01-15 23:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('leagues', '0010_week_matchup_game'),
        ('pokemons', '0007_detailedmove_alter_pokemon_name_alter_type_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('direct_kills', models.IntegerField()),
                ('indirect_kills', models.IntegerField()),
                ('deaths', models.IntegerField()),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='game_stats', to='leagues.game')),
                ('pokemon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pokemon_game_stats', to='pokemons.pokemon')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
