# Generated by Django 4.2.16 on 2025-01-21 21:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pokemons', '0008_gamestat'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Move',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=50, unique=True)),
                ('base_power', models.IntegerField()),
                ('type', models.CharField(choices=[('fire', 'Fire'), ('water', 'Water'), ('grass', 'Grass'), ('electric', 'Electric'), ('dark', 'Dark'), ('ghost', 'Ghost'), ('dragon', 'Dragon'), ('fairy', 'Fairy'), ('psychic', 'Psychic'), ('steel', 'Steel'), ('fighting', 'Fighting'), ('bug', 'Bug'), ('poison', 'Poison'), ('normal', 'Normal'), ('flying', 'Flying'), ('ground', 'Ground'), ('rock', 'Rock'), ('ice', 'Ice')], max_length=10)),
                ('accuracy', models.IntegerField()),
                ('pp', models.IntegerField()),
                ('priority', models.IntegerField()),
                ('category', models.CharField(choices=[('physical', 'Physical'), ('special', 'Special'), ('status', 'Status')], max_length=8)),
                ('description', models.TextField(blank=True, null=True)),
                ('special_categories', models.TextField(blank=True, null=True)),
                ('viable', models.BooleanField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TypeEffective',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('type', models.CharField(choices=[('fire', 'Fire'), ('water', 'Water'), ('grass', 'Grass'), ('electric', 'Electric'), ('dark', 'Dark'), ('ghost', 'Ghost'), ('dragon', 'Dragon'), ('fairy', 'Fairy'), ('psychic', 'Psychic'), ('steel', 'Steel'), ('fighting', 'Fighting'), ('bug', 'Bug'), ('poison', 'Poison'), ('normal', 'Normal'), ('flying', 'Flying'), ('ground', 'Ground'), ('rock', 'Rock'), ('ice', 'Ice')], max_length=10)),
                ('value', models.FloatField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='pokemonability',
            name='pokemon',
        ),
        migrations.RemoveField(
            model_name='pokemoncoveragemove',
            name='pokemon',
        ),
        migrations.RemoveField(
            model_name='pokemoncoveragemove',
            name='type',
        ),
        migrations.RemoveField(
            model_name='pokemondetailedmove',
            name='detailed_move',
        ),
        migrations.RemoveField(
            model_name='pokemondetailedmove',
            name='pokemon',
        ),
        migrations.RemoveField(
            model_name='pokemonmove',
            name='pokemon',
        ),
        migrations.RemoveField(
            model_name='pokemonspecialmove',
            name='pokemon',
        ),
        migrations.RemoveField(
            model_name='pokemontype',
            name='pokemon',
        ),
        migrations.RemoveField(
            model_name='pokemontype',
            name='type',
        ),
        migrations.RemoveField(
            model_name='pokemontypeeffective',
            name='pokemon',
        ),
        migrations.RemoveField(
            model_name='pokemontypeeffective',
            name='type',
        ),
        migrations.AddField(
            model_name='pokemon',
            name='types',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='gamestat',
            name='pokemon',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='game_stats', to='pokemons.pokemon'),
        ),
        migrations.DeleteModel(
            name='DetailedMove',
        ),
        migrations.DeleteModel(
            name='PokemonAbility',
        ),
        migrations.DeleteModel(
            name='PokemonCoverageMove',
        ),
        migrations.DeleteModel(
            name='PokemonDetailedMove',
        ),
        migrations.DeleteModel(
            name='PokemonMove',
        ),
        migrations.DeleteModel(
            name='PokemonSpecialMove',
        ),
        migrations.DeleteModel(
            name='PokemonType',
        ),
        migrations.DeleteModel(
            name='PokemonTypeEffective',
        ),
        migrations.DeleteModel(
            name='Type',
        ),
        migrations.AddField(
            model_name='typeeffective',
            name='pokemon',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='type_effectives', to='pokemons.pokemon'),
        ),
        migrations.AddField(
            model_name='pokemon',
            name='abilities',
            field=models.ManyToManyField(related_name='pokemons', to='pokemons.ability'),
        ),
        migrations.AddField(
            model_name='pokemon',
            name='moves',
            field=models.ManyToManyField(related_name='pokemons', to='pokemons.move'),
        ),
    ]
